ARG GO_VERSION=1.24.2
FROM golang:${GO_VERSION} 
WORKDIR /worker

RUN apt-get update && \
    apt-get install -y vim

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.consumer.toml"]
