services:
    autocert-api:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            # Important to bind/mount your codebase dir to /app dir for live reload
            - ./:/app
        ports:
            - 8080:8080
        environment:
            DB_HOST: psql-db
        depends_on:
            - psql-db
            - rabbitmq
    autocert-cert-worker:
        build:
            context: .
            dockerfile: ./Dockerfile.cert_consumer
        volumes:
            # Important to bind/mount your codebase dir to /worker dir for live reload
            - ./:/cert_worker
        environment:
            DB_HOST: psql-db
            RABBITMQ_HOST: rabbitmq
        depends_on:
            - psql-db
            - rabbitmq
    autocert-mail-worker:
        build:
            context: .
            dockerfile: ./Dockerfile.mail_consumer
        volumes:
            # Important to bind/mount your codebase dir to /worker dir for live reload
            - ./:/mail_worker
        environment:
            DB_HOST: psql-db
            RABBITMQ_HOST: rabbitmq
        depends_on:
            - psql-db
            - rabbitmq
    psql-db:
        image: postgres
        environment:
            # Automatically create database based on the name of the database in .env file
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            # host port: postgres tcp port
            - "5432:5432"
        volumes:
            # Mount database data so that even if the container got deleted, the volume would still be there unless deleted by us
            - psql_db_data:/var/lib/postgresql/data
            # Uncomment below if you want to use an initialization script
            # - "./<your_sql_file_name_here>.sql:/docker-entrypoint-initdb.d/1.sql"
    # Service name should be use '-' instead of '_'
    # See: https://github.com/minio/minio/issues/15006#issuecomment-1141639468
    s3-minio:
        image: minio/minio:latest
        ports:
            # MinIO API endpoint
            - "9000:9000"
            # MinIO Console (optional)
            - "9001:9001"
        volumes:
            - minio_data:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            # The command starts MinIO in server mode, and the console is available on port 9001.
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            # Can remove if prod
        command: "server /data --console-address :9001"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 10s
            retries: 3
        # extra_hosts:
        # - "host.docker.internal:host-gateway"
    # https://medium.com/@kaloyanmanev/how-to-run-rabbitmq-in-docker-compose-e5baccc3e644
    rabbitmq:
        image: rabbitmq:latest
        restart: always
        ports:
            - "5672:5672" # RabbitMQ default port
            - "15672:15672" # RabbitMQ management console
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        configs:
            - source: rabbitmq-plugins
              target: /etc/rabbitmq/enabled_plugins
        volumes:
            - rabbitmq-lib:/var/lib/rabbitmq/
            - rabbitmq-log:/var/log/rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
configs:
    rabbitmq-plugins:
        content: "[rabbitmq_management]."  
volumes:
    psql_db_data:
    minio_data:
    rabbitmq-lib:
    rabbitmq-log: